name: SvelteKit CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install
    - run: npm run build
    - name: Build Docker Image
      run: docker build -t my-sveltekit-app .
    # Add steps to push Docker image to a registry and deploy
